package com.liujan.dao.entity;


import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.begin_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.end_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.day_in_week
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private int dayInWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.begin_time
     *
     * @return the value of course.begin_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.begin_time
     *
     * @param beginTime the value for course.begin_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.end_time
     *
     * @return the value of course.end_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.end_time
     *
     * @param endTime the value for course.end_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.day_in_week
     *
     * @return the value of course.day_in_week
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public int getDayInWeek() {
        return dayInWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.day_in_week
     *
     * @param dayInWeek the value for course.day_in_week
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setDayInWeek(int dayInWeek) {
        this.dayInWeek = dayInWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_id
     *
     * @return the value of course.teacher_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_id
     *
     * @param teacherId the value for course.teacher_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}