package com.liujan.dao.entity;

public class Face {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.photo
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.stu_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face.face_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private String faceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.photo
     *
     * @return the value of face.photo
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.photo
     *
     * @param photo the value for face.photo
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.stu_id
     *
     * @return the value of face.stu_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.stu_id
     *
     * @param stuId the value for face.stu_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face.face_id
     *
     * @return the value of face.face_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public String getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face.face_id
     *
     * @param faceId the value for face.face_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setFaceId(String faceId) {
        this.faceId = faceId;
    }
}