package com.liujan.dao.entity;

import java.util.Date;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.teacher_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.start_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.week
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private int week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.current
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Date current;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.course_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.teacher_id
     *
     * @return the value of info.teacher_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.teacher_id
     *
     * @param teacherId the value for info.teacher_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.start_time
     *
     * @return the value of info.start_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.start_time
     *
     * @param startTime the value for info.start_time
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.week
     *
     * @return the value of info.week
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public int getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.week
     *
     * @param week the value for info.week
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setWeek(int week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.current
     *
     * @return the value of info.current
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Date getCurrent() {
        return current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.current
     *
     * @param current the value for info.current
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setCurrent(Date current) {
        this.current = current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.course_id
     *
     * @return the value of info.course_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.course_id
     *
     * @param courseId the value for info.course_id
     *
     * @mbggenerated Sat May 07 19:22:23 CST 2016
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}